-- Ingredient enumerations

METH_INGREDIENT_WATER = 0
METH_INGREDIENT_RED_PHOSPHORUS = 1
METH_INGREDIENT_PSEUDO_EPHEDRINE = 2
METH_INGREDIENT_CHLOROFORM = 3
METH_INGREDIENT_CHLORINE = 4
METH_INGREDIENT_METHANE = 5
METH_INGREDIENT_POTASSIUM_HYDROXIDE = 6
METH_INGREDIENT_POTASSIUM_CARBONATE = 7
METH_INGREDIENT_CALCIUM_HYDROXIDE = 8
METH_INGREDIENT_PURE_EPHEDRINE = 9
METH_INGREDIENT_LYE = 10
METH_INGREDIENT_HYDROGEN_IODIDE = 11
METH_INGREDIENT_FLOUR = 12
METH_INGREDIENT_LIQUID_METH = 13

-- Purity amounts

function ReloadMethPurityAmounts()
	METH_PURITY_AMOUNT_FLOUR = math.random(1, 4)
end

hook.Add("OnGamemodeLoaded", "AdvancedMeth_OnGamemodeLoaded", ReloadMethPurityAmounts)
