AddCSLuaFile()

AML_INGREDIENTS = {
	[AML_CLASS_PSEUDO_EPHEDRINE] = {Base = AML_CLASS_BASE_INGREDIENT, PrintName = AML_NAME_PSEUDO_EPHEDRINE, Model = AML_MODEL_PSEUDO_EPHEDRINE},
	[AML_CLASS_PURE_EPHEDRINE] = {Base = AML_CLASS_BASE_INGREDIENT, PrintName = AML_NAME_PURE_EPHEDRINE, Model = AML_MODEL_PURE_EPHEDRINE},
	[AML_CLASS_RED_PHOSPHORUS] = {Base = AML_CLASS_BASE_INGREDIENT, PrintName = AML_NAME_RED_PHOSPHORUS, Model = AML_MODEL_RED_PHOSPHORUS},
	[AML_CLASS_HYDROGEN_IODIDE] = {Base = AML_CLASS_BASE_INGREDIENT, PrintName = AML_NAME_HYDROGEN_IODIDE, Model = AML_MODEL_HYDROGEN_IODIDE},
	[AML_CLASS_CHLOROFORM] = {Base = AML_CLASS_BASE_INGREDIENT, PrintName = AML_NAME_CHLOROFORM, Model = AML_MODEL_CHLOROFORM},
	[AML_CLASS_CHLORINE] = {Base = AML_CLASS_BASE_INGREDIENT, PrintName = AML_NAME_CHLORINE, Model = AML_MODEL_CHLORINE},
	[AML_CLASS_METHANE] = {Base = AML_CLASS_BASE_INGREDIENT, PrintName = AML_NAME_METHANE, Model = AML_MODEL_METHANE},
	[AML_CLASS_POTASSIUM_HYDROXIDE] = {Base = AML_CLASS_BASE_INGREDIENT, PrintName = AML_NAME_POTASSIUM_HYDROXIDE, Model = AML_MODEL_POTASSIUM_HYDROXIDE},
	[AML_CLASS_POTASSIUM_CARBONATE] = {Base = AML_CLASS_BASE_INGREDIENT, PrintName = AML_NAME_POTASSIUM_CARBONATE, Model = AML_MODEL_POTASSIUM_CARBONATE},
	[AML_CLASS_CALCIUM_HYDROXIDE] = {Base = AML_CLASS_BASE_INGREDIENT, PrintName = AML_NAME_CALCIUM_HYDROXIDE, Model = AML_MODEL_CALCIUM_HYDROXIDE},
	[AML_CLASS_WATER] = {Base = AML_CLASS_BASE_INGREDIENT, PrintName = AML_NAME_WATER, Model = AML_MODEL_WATER},
	[AML_CLASS_FLOUR] = {Base = AML_CLASS_BASE_INGREDIENT, PrintName = AML_NAME_FLOUR, Model = AML_MODEL_FLOUR},
}

DEFINE_BASECLASS(AML_CLASS_BASE_INGREDIENT)

print(AML_PREFIX.."Registering ingredient entites...")

for k, v in pairs(AML_INGREDIENTS) do
	scripted_ents.Register(v, k)
	print(AML_PREFIX.."Registered ingredient: ")
end

print(AML_PREFIX.."Ingredient entities registered!")